# Generated by Django 5.2.2 on 2025-06-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
