# Generated by Django 5.2.2 on 2025-06-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_biodata_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='student_image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
